/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from SDK.Core.DashboardResponse */
export type DashboardResponse = {
    /** Transpiled from int */
    formTemplateCategoryCount: number;
    /** Transpiled from int */
    formTemplateCategoryBootcampFormsCount: number;
    /** Transpiled from int */
    formTemplateCategoryExamsFormsCount: number;
    /** Transpiled from int */
    formTemplateCategoryOthersCount: number;
    /** Transpiled from int */
    formTemplateCount: number;
    /** Transpiled from int */
    formTemplateBootcampFormsCount: number;
    /** Transpiled from int */
    formTemplateExamsFormsCount: number;
    /** Transpiled from int */
    formTemplateOthersCount: number;
    /** Transpiled from int */
    formTemplateBootcampFormsActiveCount: number;
    /** Transpiled from int */
    formTemplateExamsFormsActiveCount: number;
    /** Transpiled from int */
    formTemplateOthersActiveCount: number;
}

/** Transpiled from SDK.Core.ErrorModel */
export type ErrorModel = {
    /** Transpiled from System.Collections.Generic.Dictionary<string, string[]>? */
    errors?: { [key: string]: string[] };
    /** Transpiled from string? */
    type?: string;
    /** Transpiled from string? */
    title?: string;
    /** Transpiled from int */
    status?: number;
    /** Transpiled from string? */
    traceId?: string;
}

/** Transpiled from SDK.Core.FormTemplateOptions */
export type FormTemplateOptions = {
    /** Transpiled from SDK.Core.QuestionTypes */
    bootcamp: QuestionTypes;
    /** Transpiled from SDK.Core.QuestionTypes */
    exams: QuestionTypes;
    /** Transpiled from SDK.Core.QuestionTypes */
    others: QuestionTypes;
}

/** Transpiled from SDK.Core.LookupDictionary */
export type LookupDictionary = {
    /** Transpiled from string */
    id: string;
    /** Transpiled from string */
    text: string;
}

/** Transpiled from SDK.Core.Pagination */
export type Pagination = {
    /** Transpiled from int */
    offset: number;
    /** Transpiled from int */
    limit: number;
    /** Transpiled from int */
    total: number;
    /** Transpiled from int */
    totalPages: number;
}

/** Transpiled from SDK.Core.QuestionTypes */
export type QuestionTypes = {
    /** Transpiled from bool */
    text: boolean;
    /** Transpiled from bool */
    longText: boolean;
    /** Transpiled from bool */
    nationalId: boolean;
    /** Transpiled from bool */
    email: boolean;
    /** Transpiled from bool */
    number: boolean;
    /** Transpiled from bool */
    radio: boolean;
    /** Transpiled from bool */
    dropdown: boolean;
    /** Transpiled from bool */
    checkBox: boolean;
    /** Transpiled from bool */
    date: boolean;
    /** Transpiled from bool */
    file: boolean;
    /** Transpiled from bool */
    slider: boolean;
}

/** Transpiled from SDK.Core.SingleErrorModel */
export type SingleErrorModel = {
    /** Transpiled from string? */
    errorCode?: string;
    /** Transpiled from string? */
    errorMessage?: string;
    /** Transpiled from string? */
    traceId?: string;
}

