/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { CategoryType, PublishState, QuestionType, FileAcceptType, SingleChoiceType, TextType } from './SDK.Core.Enums';

/** Transpiled from SDK.Core.Models.FormTemplateCategoryDto */
export type FormTemplateCategoryDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    name: string;
    /** Transpiled from SDK.Core.Enums.CategoryType */
    categoryType: CategoryType;
    /** Transpiled from bool */
    isActive: boolean;
}

export type ExamAdvancedOptionDto = {

    duration: string | null;
    requireAuthentication: boolean;
    questionRandomize: boolean;
    questionPerPage: number;
    timePerPage: string | null;
    canGoBack: boolean;
}

/** Transpiled from SDK.Core.Models.FormTemplateDto */
export type FormTemplateDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from bool */
    isActive: boolean;
    /** Transpiled from SDK.Core.Enums.PublishState */
    publishState: PublishState;
    /** Transpiled from System.Guid */
    formTemplateCategoryId: string;
    CreatedAt: string;
    /** Transpiled from SDK.Core.Models.FormTemplateCategoryDto? */
    formTemplateCategory?: FormTemplateCategoryDto;
    /** Transpiled from System.Collections.Generic.List<SDK.Core.Models.FormTemplateQuestionDto> */
    formTemplateQuestions: FormTemplateQuestionDto[];
}

/** Transpiled from SDK.Core.Models.FormTemplateQuestionDto */
export type FormTemplateQuestionDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    formTemplateId: string;
    /** Transpiled from SDK.Core.Models.FormTemplateDto? */
    formTemplate?: FormTemplateDto;
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
    /** Transpiled from string? */
    fieldName?: string;
    /** Transpiled from bool */
    isRequired: boolean;
    CorrectAnwser?: string;
    /** Transpiled from SDK.Core.Models.ShowConditionDto? */
    showCondition?: ShowConditionDto;
    /** Transpiled from SDK.Core.Enums.QuestionType */
    questionType: QuestionType;
    /** Transpiled from System.Guid */
    formTemplateSectionId?: string;
    /** Transpiled from SDK.Core.Models.FormTemplateSectionDto? */
    formTemplateSection?: FormTemplateSectionDto;
    /** Transpiled from SDK.Core.Models.QuestionOptionNumberDto */
    questionOptionNumber: QuestionOptionNumberDto;
    /** Transpiled from SDK.Core.Models.QuestionOptionSingleChoiceDto */
    questionOptionSingleChoice: QuestionOptionSingleChoiceDto;
    /** Transpiled from SDK.Core.Models.QuestionOptionMultipleChoiceDto */
    questionOptionMultipleChoice: QuestionOptionMultipleChoiceDto;
    /** Transpiled from SDK.Core.Models.QuestionOptionTextDto */
    questionOptionText: QuestionOptionTextDto;
    /** Transpiled from SDK.Core.Models.QuestionOptionDateDto */
    questionOptionDate: QuestionOptionDateDto;
    /** Transpiled from SDK.Core.Models.QuestionOptionFileDto */
    questionOptionFile: QuestionOptionFileDto;
    /** Transpiled from SDK.Core.Models.QuestionOptionSliderDto */
    questionOptionSlider: QuestionOptionSliderDto;
}

/** Transpiled from SDK.Core.Models.FormTemplateSectionDto */
export type FormTemplateSectionDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
}

/** Transpiled from SDK.Core.Models.QuestionOptionDateDto */
export type QuestionOptionDateDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from string? */
    placeHolder?: string;
    /** Transpiled from System.DateTime */
    minDate?: (Date | string);
    /** Transpiled from System.DateTime */
    maxDate?: (Date | string);
    /** Transpiled from System.DateTime */
    minTime?: (Date | string);
    /** Transpiled from System.DateTime */
    maxTime?: (Date | string);
    /** Transpiled from bool */
    minToday?: boolean;
    /** Transpiled from bool */
    maxToday?: boolean;
    /** Transpiled from System.DateTime */
    defaultValue?: (Date | string);
    /** Transpiled from bool */
    allowTime: boolean;
}

/** Transpiled from SDK.Core.Models.QuestionOptionFileDto */
export type QuestionOptionFileDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from string? */
    placeHolder?: string;
    /** Transpiled from SDK.Core.Enums.FileAcceptType */
    fileAcceptType: FileAcceptType;
    /** Transpiled from decimal */
    maxSizeInMb?: number;
    /** Transpiled from int */
    maxFileCount: number;
}

/** Transpiled from SDK.Core.Models.QuestionOptionMultipleChoiceDto */
export type QuestionOptionMultipleChoiceDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from System.Collections.Generic.HashSet<string> */
    options: string[];
    /** Transpiled from System.Collections.Generic.HashSet<string>? */
    defaultValues?: string[];
}

/** Transpiled from SDK.Core.Models.QuestionOptionNumberDto */
export type QuestionOptionNumberDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from string? */
    placeHolder?: string;
    /** Transpiled from double */
    min?: number;
    /** Transpiled from double */
    max?: number;
    /** Transpiled from double */
    step?: number;
    /** Transpiled from double */
    defaultValue?: number;
    /** Transpiled from bool */
    allowDecimal?: boolean;
    /** Transpiled from bool */
    allowNegative?: boolean;
}

/** Transpiled from SDK.Core.Models.QuestionOptionSingleChoiceDto */
export type QuestionOptionSingleChoiceDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from SDK.Core.Enums.SingleChoiceType */
    singleChoiceType: SingleChoiceType;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from System.Collections.Generic.HashSet<string> */
    options: string[];
    /** Transpiled from string? */
    defaultValue?: string;
}

/** Transpiled from SDK.Core.Models.QuestionOptionSliderDto */
export type QuestionOptionSliderDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from System.Collections.Generic.Dictionary<decimal, string> */
    steps: { [key: number]: string };
    /** Transpiled from decimal */
    defaultValue?: number;
}

/** Transpiled from SDK.Core.Models.QuestionOptionTextDto */
export type QuestionOptionTextDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from string? */
    placeHolder?: string;
    /** Transpiled from int */
    minLength?: number;
    /** Transpiled from int */
    maxLength?: number;
    /** Transpiled from string? */
    defaultValue?: string;
    /** Transpiled from SDK.Core.Enums.TextType */
    textType: TextType;
}

/** Transpiled from SDK.Core.Models.ShowConditionDto */
export type ShowConditionDto = {
    /** Transpiled from System.Guid */
    formTemplateQuestionId: string;
    /** Transpiled from string */
    value: string;
}

