/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from SDK.Core.Enums.CategoryType */
export enum CategoryType {
    BootcampForms = 0,
    ExamsForms = 1,
    Other = 2,
}

/** Transpiled from SDK.Core.Enums.FileAcceptType */
export enum FileAcceptType {
    Any = 0,
    Images = 1,
    Documents = 2,
    Audio = 3,
    Video = 4,
    Compressions = 5,
}

/** Transpiled from SDK.Core.Enums.PublishState */
export enum PublishState {
    Draft = 0,
    Published = 1,
}

/** Transpiled from SDK.Core.Enums.QuestionType */
export enum QuestionType {
    Number = 1,
    Text = 2,
    Radio = 3,
    CheckBox = 4,
    Date = 5,
    File = 6,
    Slider = 7,
}

/** Transpiled from SDK.Core.Enums.ShowCondition */
export type ShowCondition = {
    /** Transpiled from System.Guid */
    formTemplateQuestionId: string;
    /** Transpiled from string */
    value: string;
}

/** Transpiled from SDK.Core.Enums.SingleChoiceType */
export enum SingleChoiceType {
    Radio = 1,
    Dropdown = 2,
}

/** Transpiled from SDK.Core.Enums.TextType */
export enum TextType {
    Text = 1,
    TextArea = 2,
    Email = 3,
    NationalId = 4,
    Phone = 5,
    Url = 6,
}

