/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import {CategoryType, ShowCondition, FileAcceptType, TextType} from './SDK.Core.Enums';
import {ExamAdvancedOptionDto} from "./SDK.Core.Models";

/** Transpiled from SDK.Core.Commands.CreateFormTemplateCategoryCommand */
export type CreateFormTemplateCategoryCommand = {
    /** Transpiled from string? */
    name?: string;
    /** Transpiled from SDK.Core.Enums.CategoryType */
    categoryType: CategoryType;
    /** Transpiled from bool */
    isActive: boolean;
}

/** Transpiled from SDK.Core.Commands.CreateFormTemplateCommand */
export type CreateFormTemplateCommand = {
    /** Transpiled from string? */
    title?: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from bool */
    isActive: boolean;
    categoryType: CategoryType;
    /** Transpiled from System.Guid */
    formTemplateCategoryId: string;
    examAdvancedOption_Duration: string | null;
    examAdvancedOption_RequireAuthentication: boolean;
    examAdvancedOption_QuestionRandomize: boolean;
    examAdvancedOption_QuestionPerPage: number;
    examAdvancedOption_TimePerPage: string | null;
    examAdvancedOption_CanGoBack: boolean;
    /** Transpiled from System.Collections.Generic.Dictionary<string, SDK.Core.Commands.CreateQuestionOptionNumberCommand> */
    questionOptionNumbers: { [key: string]: CreateQuestionOptionNumberCommand };
    /** Transpiled from System.Collections.Generic.Dictionary<string, SDK.Core.Commands.CreateQuestionOptionSliderCommand> */
    questionOptionSliders: { [key: string]: CreateQuestionOptionSliderCommand };
    /** Transpiled from System.Collections.Generic.Dictionary<string, SDK.Core.Commands.CreateQuestionOptionSingleChoiceCommand> */
    questionOptionSingleChoices: { [key: string]: CreateQuestionOptionSingleChoiceCommand };
    /** Transpiled from System.Collections.Generic.Dictionary<string, SDK.Core.Commands.CreateQuestionOptionMultipleChoiceCommand> */
    questionOptionMultipleChoices: { [key: string]: CreateQuestionOptionMultipleChoiceCommand };
    /** Transpiled from System.Collections.Generic.Dictionary<string, SDK.Core.Commands.CreateQuestionOptionDateCommand> */
    questionOptionDates: { [key: string]: CreateQuestionOptionDateCommand };
    /** Transpiled from System.Collections.Generic.Dictionary<string, SDK.Core.Commands.CreateQuestionOptionTextCommand> */
    questionOptionTexts: { [key: string]: CreateQuestionOptionTextCommand };
    /** Transpiled from System.Collections.Generic.Dictionary<string, SDK.Core.Commands.CreateQuestionOptionFileCommand> */
    questionOptionFiles: { [key: string]: CreateQuestionOptionFileCommand };
    /** Transpiled from SDK.Core.Commands.CreateQuestionOptionTextCommand */
    questionOptionTextAsText: CreateQuestionOptionTextCommand | null;
    /** Transpiled from SDK.Core.Commands.CreateQuestionOptionTextCommand */
    questionOptionTextAsTextArea: CreateQuestionOptionTextCommand | null;
    /** Transpiled from SDK.Core.Commands.CreateQuestionOptionTextCommand */
    questionOptionTextAsEmail: CreateQuestionOptionTextCommand | null;
    /** Transpiled from SDK.Core.Commands.CreateQuestionOptionTextCommand */
    questionOptionTextAsNationalId: CreateQuestionOptionTextCommand | null;
    /** Transpiled from SDK.Core.Commands.CreateQuestionOptionSingleChoiceCommand */
    questionSingleChoiceRadio: CreateQuestionOptionSingleChoiceCommand | null;
    /** Transpiled from SDK.Core.Commands.CreateQuestionOptionSingleChoiceCommand */
    questionSingleChoiceSelect: CreateQuestionOptionSingleChoiceCommand | null;
}

/** Transpiled from SDK.Core.Commands.CreateQuestionOptionNumberCommand */
export type CreateQuestionOptionNumberCommand = {
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
    /** Transpiled from string? */
    fieldName?: string;
    /** Transpiled from bool */
    isRequired: boolean;
    /** Transpiled from SDK.Core.Enums.ShowCondition? */
    showCondition?: ShowCondition;
    /** Transpiled from int */
    questionType: number;
    /** Transpiled from System.Guid */
    formTemplateSectionId?: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from string? */
    placeHolder?: string;
    /** Transpiled from double */
    min?: number;
    /** Transpiled from double */
    max?: number;
    /** Transpiled from double */
    step?: number;
    /** Transpiled from double */
    defaultValue?: number;
    /** Transpiled from bool */
    allowDecimal?: boolean;
    /** Transpiled from bool */
    allowNegative?: boolean;
}

/** Transpiled from SDK.Core.Commands.CreateQuestionOptionSliderCommand */
export type CreateQuestionOptionSliderCommand = {
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
    /** Transpiled from string? */
    fieldName?: string;
    /** Transpiled from bool */
    isRequired: boolean;
    /** Transpiled from SDK.Core.Enums.ShowCondition? */
    showCondition?: ShowCondition;
    /** Transpiled from int */
    questionType: number;
    /** Transpiled from System.Guid */
    formTemplateSectionId?: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from System.Collections.Generic.Dictionary<decimal, string> */
    steps: { [key: number]: string };
    /** Transpiled from decimal */
    defaultValue?: number;
}

/** Transpiled from SDK.Core.Commands.CreateQuestionOptionSingleChoiceCommand */
export type CreateQuestionOptionSingleChoiceCommand = {
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
    /** Transpiled from string? */
    fieldName?: string;
    /** Transpiled from bool */
    isRequired: boolean;
    /** Transpiled from SDK.Core.Enums.ShowCondition? */
    showCondition?: ShowCondition;
    /** Transpiled from int */
    questionType: number;
    /** Transpiled from System.Guid */
    formTemplateSectionId?: string;
    /** Transpiled from int */
    singleChoiceType: number;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from string[]? */
    options?: string[];
    /** Transpiled from string? */
    defaultValue?: string;
}

/** Transpiled from SDK.Core.Commands.CreateQuestionOptionMultipleChoiceCommand */
export type CreateQuestionOptionMultipleChoiceCommand = {
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
    /** Transpiled from string? */
    fieldName?: string;
    /** Transpiled from bool */
    isRequired: boolean;
    /** Transpiled from SDK.Core.Enums.ShowCondition? */
    showCondition?: ShowCondition;
    /** Transpiled from int */
    questionType: number;
    /** Transpiled from System.Guid */
    formTemplateSectionId?: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from System.Collections.Generic.HashSet<string> */
    options: string[];
    /** Transpiled from System.Collections.Generic.HashSet<string>? */
    defaultValues?: string[];
}

/** Transpiled from SDK.Core.Commands.CreateQuestionOptionDateCommand */
export type CreateQuestionOptionDateCommand = {
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
    /** Transpiled from string? */
    fieldName?: string;
    /** Transpiled from bool */
    isRequired: boolean;
    /** Transpiled from SDK.Core.Enums.ShowCondition? */
    showCondition?: ShowCondition;
    /** Transpiled from int */
    questionType: number;
    /** Transpiled from System.Guid */
    formTemplateSectionId?: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from string? */
    placeHolder?: string;
    /** Transpiled from System.DateTime */
    minDate?: (Date | string);
    /** Transpiled from System.DateTime */
    maxDate?: (Date | string);
    /** Transpiled from System.DateTime */
    minTime?: (Date | string);
    /** Transpiled from System.DateTime */
    maxTime?: (Date | string);
    /** Transpiled from bool */
    minToday?: boolean;
    /** Transpiled from bool */
    maxToday?: boolean;
    /** Transpiled from System.DateTime */
    defaultValue?: (Date | string);
    /** Transpiled from bool */
    allowTime: boolean;
}

/** Transpiled from SDK.Core.Commands.CreateQuestionOptionTextCommand */
export type CreateQuestionOptionTextCommand = {
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
    /** Transpiled from string? */
    fieldName?: string;
    /** Transpiled from bool */
    isRequired: boolean;
    /** Transpiled from SDK.Core.Enums.ShowCondition? */
    showCondition?: ShowCondition;
    /** Transpiled from int */
    questionType: number;
    /** Transpiled from System.Guid */
    formTemplateSectionId?: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from string? */
    placeHolder?: string;
    /** Transpiled from int */
    minLength?: number;
    /** Transpiled from int */
    maxLength?: number;
    /** Transpiled from string? */
    defaultValue?: string;
    /** Transpiled from int */
    textType: number;
}

/** Transpiled from SDK.Core.Commands.CreateQuestionOptionFileCommand */
export type CreateQuestionOptionFileCommand = {
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
    /** Transpiled from string? */
    fieldName?: string;
    /** Transpiled from bool */
    isRequired: boolean;
    /** Transpiled from SDK.Core.Enums.ShowCondition? */
    showCondition?: ShowCondition;
    /** Transpiled from int */
    questionType: number;
    /** Transpiled from System.Guid */
    formTemplateSectionId?: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from string? */
    placeHolder?: string;
    /** Transpiled from SDK.Core.Enums.FileAcceptType */
    fileAcceptType: FileAcceptType;
    /** Transpiled from decimal */
    maxSizeInMb?: number;
    /** Transpiled from int */
    maxFileCount: number;
}

/** Transpiled from SDK.Core.Commands.CreateFormTemplateSectionCommand */
export type CreateFormTemplateSectionCommand = {
    /** Transpiled from string? */
    title?: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order?: number;
}

/** Transpiled from SDK.Core.Commands.DeleteFormTemplateCategoryCommand */
export type DeleteFormTemplateCategoryCommand = {
    /** Transpiled from System.Guid */
    formTemplateCategoryId: string;
}

/** Transpiled from SDK.Core.Commands.DeleteFormTemplateCommand */
export type DeleteFormTemplateCommand = {
    /** Transpiled from System.Guid */
    formTemplateId: string;
}

/** Transpiled from SDK.Core.Commands.DeleteFormTemplateSectionCommand */
export type DeleteFormTemplateSectionCommand = {
    /** Transpiled from System.Guid */
    formTemplateSectionId: string;
}

/** Transpiled from SDK.Core.Commands.PublishFormTemplateCommand */
export type PublishFormTemplateCommand = {
    /** Transpiled from System.Guid */
    formTemplateId: string;
}

/** Transpiled from SDK.Core.Commands.SetActiveFormTemplateCommand */
export type SetActiveFormTemplateCommand = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from bool */
    isActive: boolean;
}

/** Transpiled from SDK.Core.Commands.UnPublishFormTemplateCommand */
export type UnPublishFormTemplateCommand = {
    /** Transpiled from System.Guid */
    formTemplateId: string;
}

/** Transpiled from SDK.Core.Commands.UpdateFormTemplateCategoryCommand */
export type UpdateFormTemplateCategoryCommand = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string? */
    name?: string;
    /** Transpiled from SDK.Core.Enums.CategoryType */
    categoryType: CategoryType;
    /** Transpiled from bool */
    isActive: boolean;
}

/** Transpiled from SDK.Core.Commands.UpdateFormTemplateCommand */
export type UpdateFormTemplateCommand = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    title: string;
    /** Transpiled from string */
    description: string;
    /** Transpiled from bool */
    isActive: boolean;
    categoryType: CategoryType;
    /** Transpiled from System.Guid */
    formTemplateCategoryId: string;
    examAdvancedOption_Duration: string | null;
    examAdvancedOption_RequireAuthentication: boolean;
    examAdvancedOption_QuestionRandomize: boolean;
    examAdvancedOption_QuestionPerPage: number;
    examAdvancedOption_TimePerPage: string | null;
    examAdvancedOption_CanGoBack: boolean;
    /** Transpiled from System.Collections.Generic.Dictionary<string, SDK.Core.Commands.UpdateQuestionOptionNumberCommand> */
    questionOptionNumbers: { [key: string]: UpdateQuestionOptionNumberCommand };
    /** Transpiled from System.Collections.Generic.Dictionary<string, SDK.Core.Commands.UpdateQuestionOptionSliderCommand> */
    questionOptionSliders: { [key: string]: UpdateQuestionOptionSliderCommand };
    /** Transpiled from System.Collections.Generic.Dictionary<string, SDK.Core.Commands.UpdateQuestionOptionSingleChoiceCommand> */
    questionOptionSingleChoices: { [key: string]: UpdateQuestionOptionSingleChoiceCommand };
    /** Transpiled from System.Collections.Generic.Dictionary<string, SDK.Core.Commands.UpdateQuestionOptionMultipleChoiceCommand> */
    questionOptionMultipleChoices: { [key: string]: UpdateQuestionOptionMultipleChoiceCommand };
    /** Transpiled from System.Collections.Generic.Dictionary<string, SDK.Core.Commands.UpdateQuestionOptionDateCommand> */
    questionOptionDates: { [key: string]: UpdateQuestionOptionDateCommand };
    /** Transpiled from System.Collections.Generic.Dictionary<string, SDK.Core.Commands.UpdateQuestionOptionTextCommand> */
    questionOptionTexts: { [key: string]: UpdateQuestionOptionTextCommand };
    /** Transpiled from System.Collections.Generic.Dictionary<string, SDK.Core.Commands.UpdateQuestionOptionFileCommand> */
    questionOptionFiles: { [key: string]: UpdateQuestionOptionFileCommand };
    /** Transpiled from SDK.Core.Commands.UpdateQuestionOptionTextCommand */
    questionOptionTextAsText: UpdateQuestionOptionTextCommand | null;
    /** Transpiled from SDK.Core.Commands.UpdateQuestionOptionTextCommand */
    questionOptionTextAsTextArea: UpdateQuestionOptionTextCommand | null;
    /** Transpiled from SDK.Core.Commands.UpdateQuestionOptionTextCommand */
    questionOptionTextAsEmail: UpdateQuestionOptionTextCommand | null;
    /** Transpiled from SDK.Core.Commands.UpdateQuestionOptionTextCommand */
    questionOptionTextAsNationalId: UpdateQuestionOptionTextCommand | null;
    /** Transpiled from SDK.Core.Commands.UpdateQuestionOptionSingleChoiceCommand */
    questionSingleChoiceRadio: UpdateQuestionOptionSingleChoiceCommand | null;
    /** Transpiled from SDK.Core.Commands.UpdateQuestionOptionSingleChoiceCommand */
    questionSingleChoiceSelect: UpdateQuestionOptionSingleChoiceCommand | null;
}

/** Transpiled from SDK.Core.Commands.UpdateQuestionOptionNumberCommand */
export type UpdateQuestionOptionNumberCommand = {
    /** Transpiled from System.Guid */
    id?: string;
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
    /** Transpiled from string? */
    fieldName?: string;
    /** Transpiled from bool */
    isRequired: boolean;
    /** Transpiled from string? */
    correctAnswer?: string;
    /** Transpiled from SDK.Core.Enums.ShowCondition? */
    showCondition?: ShowCondition;
    /** Transpiled from int */
    questionType: number;
    /** Transpiled from System.Guid */
    formTemplateSectionId?: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from string? */
    placeHolder?: string;
    /** Transpiled from double */
    min?: number;
    /** Transpiled from double */
    max?: number;
    /** Transpiled from double */
    step?: number;
    /** Transpiled from double */
    defaultValue?: number;
    /** Transpiled from bool */
    allowDecimal?: boolean;
    /** Transpiled from bool */
    allowNegative?: boolean;
}

/** Transpiled from SDK.Core.Commands.UpdateQuestionOptionSliderCommand */
export type UpdateQuestionOptionSliderCommand = {
    /** Transpiled from System.Guid */
    id?: string;
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
    /** Transpiled from string? */
    fieldName?: string;
    /** Transpiled from bool */
    isRequired: boolean;
    /** Transpiled from string? */
    correctAnswer?: string;
    /** Transpiled from SDK.Core.Enums.ShowCondition? */
    showCondition?: ShowCondition;
    /** Transpiled from int */
    questionType: number;
    /** Transpiled from System.Guid */
    formTemplateSectionId?: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from System.Collections.Generic.Dictionary<decimal, string> */
    steps: { [key: number]: string };
    /** Transpiled from decimal */
    defaultValue?: number;
}

/** Transpiled from SDK.Core.Commands.UpdateQuestionOptionSingleChoiceCommand */
export type UpdateQuestionOptionSingleChoiceCommand = {
    /** Transpiled from System.Guid */
    id?: string;
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
    /** Transpiled from string? */
    fieldName?: string;
    /** Transpiled from bool */
    isRequired: boolean;
    /** Transpiled from string? */
    correctAnswer?: string;
    /** Transpiled from SDK.Core.Enums.ShowCondition? */
    showCondition?: ShowCondition;
    /** Transpiled from int */
    questionType: number;
    /** Transpiled from System.Guid */
    formTemplateSectionId?: string;
    /** Transpiled from int */
    singleChoiceType: number;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from string[]? */
    options?: string[];
    /** Transpiled from string? */
    defaultValue?: string;
}

/** Transpiled from SDK.Core.Commands.UpdateQuestionOptionMultipleChoiceCommand */
export type UpdateQuestionOptionMultipleChoiceCommand = {
    /** Transpiled from System.Guid */
    id?: string;
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
    /** Transpiled from string? */
    fieldName?: string;
    /** Transpiled from bool */
    isRequired: boolean;
    /** Transpiled from string? */
    correctAnswer?: string;
    /** Transpiled from SDK.Core.Enums.ShowCondition? */
    showCondition?: ShowCondition;
    /** Transpiled from int */
    questionType: number;
    /** Transpiled from System.Guid */
    formTemplateSectionId?: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from string[]? */
    options?: string[];
    /** Transpiled from string[]? */
    defaultValues?: string[];
}

/** Transpiled from SDK.Core.Commands.UpdateQuestionOptionDateCommand */
export type UpdateQuestionOptionDateCommand = {
    /** Transpiled from System.Guid */
    id?: string;
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
    /** Transpiled from string? */
    fieldName?: string;
    /** Transpiled from bool */
    isRequired: boolean;
    /** Transpiled from string? */
    correctAnswer?: string;
    /** Transpiled from SDK.Core.Enums.ShowCondition? */
    showCondition?: ShowCondition;
    /** Transpiled from int */
    questionType: number;
    /** Transpiled from System.Guid */
    formTemplateSectionId?: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from string? */
    placeHolder?: string;
    /** Transpiled from System.DateTime */
    minDate?: (Date | string);
    /** Transpiled from System.DateTime */
    maxDate?: (Date | string);
    /** Transpiled from System.DateTime */
    minTime?: (Date | string);
    /** Transpiled from System.DateTime */
    maxTime?: (Date | string);
    /** Transpiled from bool */
    minToday?: boolean;
    /** Transpiled from bool */
    maxToday?: boolean;
    /** Transpiled from System.DateTime */
    defaultValue?: (Date | string);
    /** Transpiled from bool */
    allowTime: boolean;
}

/** Transpiled from SDK.Core.Commands.UpdateQuestionOptionTextCommand */
export type UpdateQuestionOptionTextCommand = {
    /** Transpiled from System.Guid */
    id?: string;
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
    /** Transpiled from string? */
    fieldName?: string;
    /** Transpiled from bool */
    isRequired: boolean;
    /** Transpiled from string? */
    correctAnswer?: string;
    /** Transpiled from SDK.Core.Enums.ShowCondition? */
    showCondition?: ShowCondition;
    /** Transpiled from int */
    questionType: number;
    /** Transpiled from System.Guid */
    formTemplateSectionId?: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from string? */
    placeHolder?: string;
    /** Transpiled from int */
    minLength?: number;
    /** Transpiled from int */
    maxLength?: number;
    /** Transpiled from string? */
    defaultValue?: string;
    /** Transpiled from SDK.Core.Enums.TextType */
    textType: TextType;
}

/** Transpiled from SDK.Core.Commands.UpdateQuestionOptionFileCommand */
export type UpdateQuestionOptionFileCommand = {
    /** Transpiled from System.Guid */
    id?: string;
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
    /** Transpiled from string? */
    fieldName?: string;
    /** Transpiled from bool */
    isRequired: boolean;
    /** Transpiled from string? */
    correctAnswer?: string;
    /** Transpiled from SDK.Core.Enums.ShowCondition? */
    showCondition?: ShowCondition;
    /** Transpiled from int */
    questionType: number;
    /** Transpiled from System.Guid */
    formTemplateSectionId?: string;
    /** Transpiled from string? */
    label?: string;
    /** Transpiled from string? */
    placeHolder?: string;
    /** Transpiled from SDK.Core.Enums.FileAcceptType */
    fileAcceptType: FileAcceptType;
    /** Transpiled from decimal */
    maxSizeInMb?: number;
    /** Transpiled from int */
    maxFileCount: number;
}

/** Transpiled from SDK.Core.Commands.UpdateFormTemplateSectionCommand */
export type UpdateFormTemplateSectionCommand = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string? */
    title?: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    order: number;
}

