//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDK.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SDK.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        public static string MinLengthError {
            get {
                return ResourceManager.GetString("MinLengthError", resourceCulture);
            }
        }
        
        public static string MaxLengthError {
            get {
                return ResourceManager.GetString("MaxLengthError", resourceCulture);
            }
        }
        
        public static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        public static string FormTemplateCommand_FormTemplateCategory {
            get {
                return ResourceManager.GetString("FormTemplateCommand_FormTemplateCategory", resourceCulture);
            }
        }
        
        public static string FormTemplateCommand_Title {
            get {
                return ResourceManager.GetString("FormTemplateCommand_Title", resourceCulture);
            }
        }
        
        public static string FormTemplateCommand_Description {
            get {
                return ResourceManager.GetString("FormTemplateCommand_Description", resourceCulture);
            }
        }
        
        public static string FormTemplateCommand_IsActive {
            get {
                return ResourceManager.GetString("FormTemplateCommand_IsActive", resourceCulture);
            }
        }
        
        public static string EnterYourEmailAddress {
            get {
                return ResourceManager.GetString("EnterYourEmailAddress", resourceCulture);
            }
        }
        
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        public static string EnterYourQuestion {
            get {
                return ResourceManager.GetString("EnterYourQuestion", resourceCulture);
            }
        }
        
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        public static string EnterYourNationalId {
            get {
                return ResourceManager.GetString("EnterYourNationalId", resourceCulture);
            }
        }
        
        public static string NationalId {
            get {
                return ResourceManager.GetString("NationalId", resourceCulture);
            }
        }
        
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
    }
}
