//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Application.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string _0_IsRequired {
            get {
                return ResourceManager.GetString("{0}IsRequired", resourceCulture);
            }
        }
        
        public static string _0_Invalid {
            get {
                return ResourceManager.GetString("{0}Invalid", resourceCulture);
            }
        }
        
        public static string _0_NotFound {
            get {
                return ResourceManager.GetString("{0}NotFound", resourceCulture);
            }
        }
        
        public static string _0_Exist {
            get {
                return ResourceManager.GetString("{0}Exist", resourceCulture);
            }
        }
        
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        public static string _0_FailedPleaseTryAgain {
            get {
                return ResourceManager.GetString("{0}FailedPleaseTryAgain", resourceCulture);
            }
        }
        
        public static string _0_Failed {
            get {
                return ResourceManager.GetString("{0}Failed", resourceCulture);
            }
        }
        
        public static string _0_IsTooSmall_MinimumCharactersIs_1_ {
            get {
                return ResourceManager.GetString("{0}IsTooSmall.MinimumCharactersIs{1}", resourceCulture);
            }
        }
        
        public static string _0_IsTooLong_MaximumCharactersIs_1_ {
            get {
                return ResourceManager.GetString("{0}IsTooLong.MaximumCharactersIs{1}", resourceCulture);
            }
        }
        
        public static string _0_ShouldBeBetween {
            get {
                return ResourceManager.GetString("{0}ShouldBeBetween", resourceCulture);
            }
        }
        
        public static string _0_MustBeGreaterThan_1_ {
            get {
                return ResourceManager.GetString("{0}MustBeGreaterThan{1}", resourceCulture);
            }
        }
        
        public static string _0_MustBeGreaterThanOrEqual_1_ {
            get {
                return ResourceManager.GetString("{0}MustBeGreaterThanOrEqual{1}", resourceCulture);
            }
        }
        
        public static string _0_MustBeLessThanOrEqual_1_ {
            get {
                return ResourceManager.GetString("{0}MustBeLessThanOrEqual{1}", resourceCulture);
            }
        }
        
        public static string _0_IsTooYoung {
            get {
                return ResourceManager.GetString("{0}IsTooYoung", resourceCulture);
            }
        }
        
        public static string FormTemplateCategory_Name {
            get {
                return ResourceManager.GetString("FormTemplateCategory.Name", resourceCulture);
            }
        }
        
        public static string FormTemplateId {
            get {
                return ResourceManager.GetString("FormTemplateId", resourceCulture);
            }
        }
        
        public static string FormTemplate {
            get {
                return ResourceManager.GetString("FormTemplate", resourceCulture);
            }
        }
        
        public static string _0_Failed_1_ {
            get {
                return ResourceManager.GetString("{0}Failed{1}", resourceCulture);
            }
        }
        
        public static string CheckQuestions {
            get {
                return ResourceManager.GetString("CheckQuestions", resourceCulture);
            }
        }
        
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        public static string _0_AlreadyPublished {
            get {
                return ResourceManager.GetString("{0}AlreadyPublished", resourceCulture);
            }
        }
        
        public static string _0_AlreadyUnPublished {
            get {
                return ResourceManager.GetString("{0}AlreadyUnPublished", resourceCulture);
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string FormTemplateCategoryId {
            get {
                return ResourceManager.GetString("FormTemplateCategoryId", resourceCulture);
            }
        }
        
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        public static string FormTemplateCategory {
            get {
                return ResourceManager.GetString("FormTemplateCategory", resourceCulture);
            }
        }
        
        public static string FormTemplateCategoryHasForms {
            get {
                return ResourceManager.GetString("FormTemplateCategoryHasForms", resourceCulture);
            }
        }
        
        public static string FormTemplateIsPublished {
            get {
                return ResourceManager.GetString("FormTemplateIsPublished", resourceCulture);
            }
        }
        
        public static string CorrectAnswerIsRequired {
            get {
                return ResourceManager.GetString("CorrectAnswerIsRequired", resourceCulture);
            }
        }
    }
}
